# mkdocs.yml
site_name: ECF Compass
site_description: الأداة التفاعلية للتطور الأخلاقي
site_author: Samir Baladi

theme:
  name: readthedocs

nav:
  - الصفحة الرئيسية: index.md
  - دليل الاستخدام: guide.md
  - الأساس الفلسفي: philosophy.md

markdown_extensions:
  - toc:
      permalink: true
  - tables